export const GET_NEWS_BY_SYMBOL_REQUEST = "NEWS/GET_NEWS_BY_SYMBOL_REQUEST";
export const GET_NEWS_BY_SYMBOL_SUCCESS = "NEWS/GET_NEWS_BY_SYMBOL_SUCCESS";
export const GET_NEWS_BY_SYMBOL_FAILURE = "NEWS/GET_NEWS_BY_SYMBOL_FAILURE";
