export const GET_STOCKS_BY_MARKET_REQUEST =
  "STOCKS/GET_STOCKS_BY_MARKET_REQUEST";
export const GET_STOCKS_BY_MARKET_SUCCESS =
  "STOCKS/GET_STOCKS_BY_MARKET_SUCCESS";
export const GET_STOCKS_BY_MARKET_FAILURE =
  "STOCKS/GET_STOCKS_BY_MARKET_FAILURE";

// HISTORY PRICES BY SYMBOL
export const GET_HISTORY_PRICES_BY_SYMBOL_REQUEST =
  "STOCKS/GET_HISTORY_PRICES_BY_SYMBOL_REQUEST";
export const GET_HISTORY_PRICES_BY_SYMBOL_SUCCESS =
  "STOCKS/GET_HISTORY_PRICES_BY_SYMBOL_SUCCESS";
export const GET_HISTORY_PRICES_BY_SYMBOL_FAILURE =
  "STOCKS/GET_HISTORY_PRICES_BY_SYMBOL_FAILURE";
