export const GET_STOCKS_BY_MARKET_REQUEST = "GET_STOCKS_BY_MARKET_REQUEST";
export const GET_STOCKS_BY_MARKET_SUCCESS = "GET_STOCKS_BY_MARKET_SUCCESS";
export const GET_STOCKS_BY_MARKET_FAILURE = "GET_STOCKS_BY_MARKET_FAILURE";
