export const GET_STOCKS_BY_MARKET_REQUEST = "GET_STOCKS_BY_MARKET_REQUEST";
export const GET_STOCKS_BY_MARKET_SUCCESS = "GET_STOCKS_BY_MARKET_SUCCESS";
export const GET_STOCKS_BY_MARKET_FAILURE = "GET_STOCKS_BY_MARKET_FAILURE";

// HISTORY PRICES BY SYMBOL
export const GET_HISTORY_PRICES_BY_SYMBOL_REQUEST =
  "GET_HISTORY_PRICES_BY_SYMBOL_REQUEST";
export const GET_HISTORY_PRICES_BY_SYMBOL_SUCCESS =
  "GET_HISTORY_PRICES_BY_SYMBOL_SUCCESS";
export const GET_HISTORY_PRICES_BY_SYMBOL_FAILURE =
  "GET_HISTORY_PRICES_BY_SYMBOL_FAILURE";
